const { ethers } = require("hardhat");

async function main() {
  try {
    console.log("Starting deployment...");
    
    const [deployer] = await ethers.getSigners();
    console.log("Deploying contracts with account:", deployer.address);
    
    // Get balance using provider
    const balance = await ethers.provider.getBalance(deployer.address);
    console.log("Account balance:", ethers.formatEther(balance), "ETH");
    
    // Deploy Factory
    console.log("\n1. Deploying Factory...");
    const Factory = await ethers.getContractFactory("AMMFactory");
    const factory = await Factory.deploy();
    await factory.waitForDeployment();
    const factoryAddress = await factory.getAddress();
    console.log("Factory deployed to:", factoryAddress);
    
    // Deploy Router
    console.log("\n2. Deploying Router...");
    const Router = await ethers.getContractFactory("AMMRouter");
    const router = await Router.deploy(factoryAddress);
    await router.waitForDeployment();
    const routerAddress = await router.getAddress();
    console.log("Router deployed to:", routerAddress);
    
    // Deploy Test Tokens
    console.log("\n3. Deploying Test Tokens...");
    const TestToken = await ethers.getContractFactory("TestToken");
    
    const tokenA = await TestToken.deploy("Token A", "TKNA");
    await tokenA.waitForDeployment();
    const tokenAAddress = await tokenA.getAddress();
    console.log("Token A deployed to:", tokenAAddress);
    
    const tokenB = await TestToken.deploy("Token B", "TKNB");
    await tokenB.waitForDeployment();
    const tokenBAddress = await tokenB.getAddress();
    console.log("Token B deployed to:", tokenBAddress);
    
    // Save addresses for frontend
    const addresses = {
      factory: factoryAddress,
      router: routerAddress,
      tokenA: tokenAAddress,
      tokenB: tokenBAddress
    };
    
    console.log("\n✅ Deployment complete!");
    console.log("\nAddresses for frontend:");
    console.log(JSON.stringify(addresses, null, 2));
    
    // Save to file
    const fs = require("fs");
    const path = require("path");
    
    // Create constants file for frontend
    const constantsDir = path.join(__dirname, "../frontend/src/utils");
    if (!fs.existsSync(constantsDir)) {
      fs.mkdirSync(constantsDir, { recursive: true });
    }
    
    const constantsContent = `// Auto-generated by deploy script
export const FACTORY_ADDRESS = "${factoryAddress}";
export const ROUTER_ADDRESS = "${routerAddress}";

export const TOKENS = {
  tokenA: "${tokenAAddress}",
  tokenB: "${tokenBAddress}",
};

export const NETWORK = "localhost";
`;
    
    fs.writeFileSync(
      path.join(constantsDir, "constants.js"),
      constantsContent
    );
    
    console.log("\n✅ Frontend constants saved!");
    
  } catch (error) {
    console.error("\n❌ Deployment failed!");
    console.error("Error:", error);
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
