// frontend/src/utils/constants.js
// This file is auto-generated by deploy script, but here's a version with defaults

export const FACTORY_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3"; // Default hardhat deploy address
export const ROUTER_ADDRESS = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"; // Default hardhat deploy address

export const TOKENS = {
  WETH: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  USDC: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
  DAI: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
};

export const POOLS = {
  WETH_USDC: "",
  WETH_DAI: "",
  USDC_DAI: "",
};

// Use defaults if env variables don't exist
export const ALCHEMY_KEY = process.env.REACT_APP_ALCHEMY_KEY || "";
export const WALLETCONNECT_PROJECT_ID = process.env.REACT_APP_WALLETCONNECT_PROJECT_ID || "dummy-project-id";
export const NETWORK = process.env.REACT_APP_NETWORK || "localhost";