-- Auto-generated Bitcoin Schema from getblock JSON
-- Generated by JSON to SQL Schema Generator

CREATE TABLE blocks (
    hash TEXT PRIMARY KEY NOT NULL,
    confirmations INTEGER,
    size INTEGER,
    strippedsize INTEGER,
    weight INTEGER,
    height INTEGER,
    version INTEGER,
    versionHex TEXT,
    merkleroot TEXT,
    time INTEGER,
    mediantime INTEGER,
    nonce INTEGER,
    bits TEXT,
    difficulty REAL,
    chainwork TEXT,
    nTx INTEGER,
    previousblockhash TEXT,
    nextblockhash TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    block_hash TEXT,
    txid TEXT PRIMARY KEY,
    hash TEXT NOT NULL,
    version INTEGER,
    size INTEGER,
    vsize INTEGER,
    weight INTEGER,
    locktime INTEGER,
    hex TEXT,
    fee INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (block_hash) REFERENCES blocks(hash)
);

CREATE TABLE transaction_inputs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    txid TEXT,
    coinbase TEXT,
    sequence INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (txid) REFERENCES transactions(txid)
);

CREATE TABLE transaction_outputs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    txid TEXT,
    value REAL,
    n INTEGER,
    scriptpubkey_asm TEXT,
    scriptpubkey_hex TEXT,
    scriptpubkey_reqSigs INTEGER,
    scriptpubkey_type TEXT,
    scriptpubkey_addresses TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (txid) REFERENCES transactions(txid)
);

-- Performance Indexes
CREATE INDEX idx_blocks_height ON blocks(height);
CREATE INDEX idx_blocks_time ON blocks(time);
CREATE INDEX idx_transactions_block_hash ON transactions(block_hash);
CREATE INDEX idx_transaction_inputs_txid ON transaction_inputs(txid);
CREATE INDEX idx_transaction_outputs_txid ON transaction_outputs(txid);
